apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fastapi-microservice.fullname" . }}
  labels:
    {{- include "fastapi-microservice.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "fastapi-microservice.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "fastapi-microservice.name" . }}
    spec:
      containers:
        - name: fastapi-microservice
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: ENVIRONMENT
              value: "production"

