apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "fastapi-microservice.fullname" . }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
        {{- range .paths }}
        - path: {{ . }}
          pathType: Prefix
          backend:
            service:
              name: {{ include "fastapi-microservice.fullname" $ }}
              port:
                number: {{ $.Values.service.port }}
        {{- end }}
    {{- end }}
