apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastapi-microservice.fullname" . }}
  labels:
    {{- include "fastapi-microservice.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: {{ include "fastapi-microservice.name" . }}
  type: {{ .Values.service.type }}
