trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'fastapi-microservice'
  containerRegistry: $(ACR_CONNECTION)

steps:
- task: Docker@2
  displayName: 'Login to Azure Container Registry'
  inputs:
    command: 'login'
    containerRegistry: $(containerRegistry)

- task: Docker@2
  displayName: 'Build and Push FastAPI Docker Image'
  inputs:
    command: 'buildAndPush'
    repository: '$(imageName)'
    dockerfile: 'app/fastapi/Dockerfile'
    containerRegistry: $(containerRegistry)
    tags: '$(Build.BuildId)'

- task: AzureKeyVault@2
  displayName: 'Get secrets from Azure Key Vault'
  inputs:
    connectedServiceName: $(AZURE_CONNECTION)
    keyVaultName: $(KEYVAULT_NAME)
    secretsFilter: 'docker-registry-credentials'
